modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="sigcraft"
version="0.0.1"
displayName="SigCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://notthrafn.com"
authors="Sigvaldr"
description='''
Alternate Timeline
'''

[[dependencies.sigcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




